## Torch Preliminaries

- [Reference](https://d2l.ai/chapter_preliminaries/ndarray.html)

In [1]:
import torch

In [2]:
x = torch.arange(12)

In [3]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
type(x)

torch.Tensor

In [5]:
x.shape

torch.Size([12])

In [6]:
x.numel()

12

In [7]:
x.reshape(3, 4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [8]:
x.reshape(3, -1)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [9]:
x.reshape(-1, 4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [10]:
torch.zeros((1, 1, 1))

tensor([[[0.]]])

In [11]:
torch.zeros((1, 1, 3))

tensor([[[0., 0., 0.]]])

In [12]:
torch.zeros((3, 1, 1))

tensor([[[0.]],

        [[0.]],

        [[0.]]])

In [13]:
torch.ones((2, 2, 1))

tensor([[[1.],
         [1.]],

        [[1.],
         [1.]]])

In [14]:
torch.randn(3, 3)

tensor([[-1.2718,  0.2095, -1.5442],
        [-0.9611,  0.9480, -1.2144],
        [ 0.3593,  0.7350, -0.0861]])

In [15]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])